services:

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: salon
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - salon-mysql-local:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  salon-mysql-local:
