logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: TRACE # Incoming HTTP requests
    org.springframework.jdbc.datasource.init: DEBUG
    org.springframework.jdbc.core: DEBUG # SQL
spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:mysql://${DATABASE_URL:localhost}:${DATABASE_PORT:3307}/salon
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: ${INIT_DB:always}
      schema-locations: "classpath:database-init.sql"

